---
title: "Projects"
---

Over the duration of the term, you will complete **three** projects. Each
project will focus on the **same** data you select at the beginning of the
course, but will explore the data in slightly different ways. In each of the
sections below, we describe the goals / foci of each project, the final 
deliverable, and the approximate timeline for completing the project. 

Before the term starts, you will need to choose the dataset you are interested
in working with throughout the course. Below, we describe each of the datasets
you can choose from:

- Environmental: Plastic Waste
- Health: Measles Cases
- Sports: Olympic Medals
- Geopolitical: Government Types

**Please fill out this form indicating your preferences regarding these options:**

[Link to Google Form](https://forms.gle/5G5nzoJnDoT2yFY47)

# Project 1 (Unit 1)

This project focuses on constructing longer and more complex data pipelines, 
data acquisition from APIs and webscraping, and crafting more sophisticated 
data visualizations and summary tables. 

The deliverable for the project is a stylized, publication-ready report. The
report will include an exploratory data analysis complete with styled 
visualizations and polished tables, each of which address **at least two** 
research questions posed by your group.

The approximate timeline for completing the project is:

- [Week 1](/project/week-1.qmd)
    * Acquire data
    * Pose research questions
    * Sketch out potential visualizations

- [Week 2](/project/week-2.qmd)
    * Summarize data 
    * Write functions 
    * Iterate over functions
    * Professionally format summaries 

- [Week 3](/project/week-3.qmd)
    * Acquire new country-level data using APIs and webscraping
    * Join new data with original data
    * Produce summaries or simple visualizations that incorporate new data
    
- [Week 4](/project/week-4.qmd)
    * Make two new visualizations using more complex geometries 
    * Fit a statistical model
    * Report findings from that model (professionally formatted)

- [Week 5](/project/project-1.qmd) final report is due

# Project 2 (Unit 2)

This project focuses on creating both static and dynamic (interactive) Quarto
dashboards to tell a story about your data. 

The final deliverable for the project is a dynamic Quarto dashboard which 


The approximate timeline for completing the project is:

- 


